version: '2'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    command: yarn run startdev
    ports:
     - "3000:3000"
    env_file: .env
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/name-that-tune
