version: '0.1.0'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/name-that-tune
     - /name-that-tune/node_modules
